
[2018-09-16 15:16:10] INFO [<module>: run_all.py, 6] ========================= 测试开始 =========================
[2018-09-16 15:16:10] INFO [test_user_login_normal: test_user_login.py, 19] 测试用例：test_user_login_normal
[2018-09-16 15:16:10] INFO [test_user_login_normal: test_user_login.py, 20] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 15:16:10] INFO [test_user_login_normal: test_user_login.py, 21] 请求数据：{"name":"张三","password":"123456"}
[2018-09-16 15:16:10] INFO [test_user_login_normal: test_user_login.py, 22] 期望结果：<h1>登录成功</h1>
[2018-09-16 15:16:10] INFO [test_user_login_password_wrong: test_user_login.py, 37] 测试用例：test_user_login_password_wrong
[2018-09-16 15:16:10] INFO [test_user_login_password_wrong: test_user_login.py, 38] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 15:16:10] INFO [test_user_login_password_wrong: test_user_login.py, 39] 请求数据：{'name': '张三', 'password': '1234567'}
[2018-09-16 15:16:10] INFO [test_user_login_password_wrong: test_user_login.py, 40] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-16 15:16:10] INFO [<module>: run_all.py, 12] ========================= 测试结束 =========================
[2018-09-16 15:16:43] INFO [<module>: run_all.py, 6] ========================= 测试开始 =========================
[2018-09-16 15:16:43] INFO [test_user_login_normal: test_user_login.py, 19] 测试用例：test_user_login_normal
[2018-09-16 15:16:43] INFO [test_user_login_normal: test_user_login.py, 20] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 15:16:43] INFO [test_user_login_normal: test_user_login.py, 21] 请求数据：{"name":"张三","password":"123456"}
[2018-09-16 15:16:43] INFO [test_user_login_normal: test_user_login.py, 22] 期望结果：<h1>登录成功</h1>
[2018-09-16 15:16:43] INFO [test_user_login_password_wrong: test_user_login.py, 37] 测试用例：test_user_login_password_wrong
[2018-09-16 15:16:43] INFO [test_user_login_password_wrong: test_user_login.py, 38] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 15:16:43] INFO [test_user_login_password_wrong: test_user_login.py, 39] 请求数据：{'name': '张三', 'password': '1234567'}
[2018-09-16 15:16:43] INFO [test_user_login_password_wrong: test_user_login.py, 40] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-16 15:16:43] INFO [<module>: run_all.py, 12] ========================= 测试结束 =========================
[2018-09-16 16:40:26] INFO [<module>: run_all.py, 7] ========================= 测试开始 =========================
[2018-09-16 16:40:27] INFO [test_user_login_normal: test_user_login.py, 19] 测试用例：test_user_login_normal
[2018-09-16 16:40:27] INFO [test_user_login_normal: test_user_login.py, 20] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 16:40:27] INFO [test_user_login_normal: test_user_login.py, 21] 请求数据：{"name":"张三","password":"123456"}
[2018-09-16 16:40:27] INFO [test_user_login_normal: test_user_login.py, 22] 期望结果：<h1>登录成功</h1>
[2018-09-16 16:40:27] INFO [test_user_login_password_wrong: test_user_login.py, 37] 测试用例：test_user_login_password_wrong
[2018-09-16 16:40:27] INFO [test_user_login_password_wrong: test_user_login.py, 38] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 16:40:27] INFO [test_user_login_password_wrong: test_user_login.py, 39] 请求数据：{'name': '张三', 'password': '1234567'}
[2018-09-16 16:40:27] INFO [test_user_login_password_wrong: test_user_login.py, 40] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-16 16:40:36] INFO [<module>: run_all.py, 14] 邮件已发送
[2018-09-16 16:40:36] INFO [<module>: run_all.py, 15] ========================= 测试结束 =========================
[2018-09-16 18:01:10] INFO [<module>: config.py, 42] hello
[2018-09-16 18:01:29] INFO [test_user_login_normal: test_user_login.py, 20] 测试用例：test_user_login_normal
[2018-09-16 18:01:29] INFO [test_user_login_normal: test_user_login.py, 21] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 18:01:29] INFO [test_user_login_normal: test_user_login.py, 22] 请求数据：{"name":"张三","password":"123456"}
[2018-09-16 18:01:29] INFO [test_user_login_normal: test_user_login.py, 23] 期望结果：<h1>登录成功</h1>
[2018-09-16 18:01:59] INFO [test_user_login_normal: test_user_login.py, 20] 测试用例：test_user_login_normal
[2018-09-16 18:01:59] INFO [test_user_login_normal: test_user_login.py, 21] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 18:01:59] INFO [test_user_login_normal: test_user_login.py, 22] 请求数据：{"name":"张三","password":"123456"}
[2018-09-16 18:01:59] INFO [test_user_login_normal: test_user_login.py, 23] 期望结果：<h1>登录成功</h1>
[2018-09-16 18:02:13] INFO [test_user_login_password_wrong: test_user_login.py, 38] 测试用例：test_user_login_password_wrong
[2018-09-16 18:02:13] INFO [test_user_login_password_wrong: test_user_login.py, 39] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 18:02:13] INFO [test_user_login_password_wrong: test_user_login.py, 40] 请求数据：{'name': '张三', 'password': '1234567'}
[2018-09-16 18:02:13] INFO [test_user_login_password_wrong: test_user_login.py, 41] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-16 18:07:11] INFO [<module>: run_all.py, 6] ========================= 测试开始 =========================
[2018-09-16 18:07:11] INFO [test_user_login_normal: test_user_login.py, 20] 测试用例：test_user_login_normal
[2018-09-16 18:07:11] INFO [test_user_login_normal: test_user_login.py, 21] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 18:07:11] INFO [test_user_login_normal: test_user_login.py, 22] 请求数据：{"name":"张三","password":"123456"}
[2018-09-16 18:07:11] INFO [test_user_login_normal: test_user_login.py, 23] 期望结果：<h1>登录成功</h1>
[2018-09-16 18:07:12] INFO [test_user_login_password_wrong: test_user_login.py, 38] 测试用例：test_user_login_password_wrong
[2018-09-16 18:07:12] INFO [test_user_login_password_wrong: test_user_login.py, 39] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 18:07:12] INFO [test_user_login_password_wrong: test_user_login.py, 40] 请求数据：{'name': '张三', 'password': '1234567'}
[2018-09-16 18:07:12] INFO [test_user_login_password_wrong: test_user_login.py, 41] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-16 18:07:16] INFO [<module>: run_all.py, 13] 邮件已发送
[2018-09-16 18:07:16] INFO [<module>: run_all.py, 14] ========================= 测试结束 =========================
[2018-09-16 18:14:41] INFO [<module>: run_all.py, 6] ========================= 测试开始 =========================
[2018-09-16 18:14:41] INFO [test_user_login_normal: test_user_login.py, 20] 测试用例：test_user_login_normal
[2018-09-16 18:14:41] INFO [test_user_login_normal: test_user_login.py, 21] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 18:14:41] INFO [test_user_login_normal: test_user_login.py, 22] 请求数据：{"name":"张三","password":"123456"}
[2018-09-16 18:14:41] INFO [test_user_login_normal: test_user_login.py, 23] 期望结果：<h1>登录成功</h1>
[2018-09-16 18:14:41] INFO [test_user_login_password_wrong: test_user_login.py, 38] 测试用例：test_user_login_password_wrong
[2018-09-16 18:14:41] INFO [test_user_login_password_wrong: test_user_login.py, 39] url: http://115.28.108.130:5000/api/user/login/
[2018-09-16 18:14:41] INFO [test_user_login_password_wrong: test_user_login.py, 40] 请求数据：{'name': '张三', 'password': '1234567'}
[2018-09-16 18:14:41] INFO [test_user_login_password_wrong: test_user_login.py, 41] 期望结果：<h1>失败，用户名或密码错误</h1>
